CLASSPATH=target/depbuilder-1.0.1-1.jar:\
/jhome/rthummalapenta/.m2/repository/org/eclipse/mylyn/github/org.eclipse.egit.github.core/2.1.5/org.eclipse.egit.github.core-2.1.5.jar:\
/jhome/rthummalapenta/.m2/repository/com/google/code/gson/gson/2.2.2/gson-2.2.2.jar:\
/jhome/rthummalapenta/.m2/repository/log4j/log4j/1.2.16/log4j-1.2.16.jar:\
/jhome/rthummalapenta/.m2/repository/org/apache/maven/maven-model/3.0.4/maven-model-3.0.4.jar:\:\
/jhome/rthummalapenta/.m2/repository/org/apache/maven/maven-core/3.0.4/maven-core-3.0.4.jar:\
/jhome/rthummalapenta/.m2/repository/org/apache/maven/maven-settings/3.0.4/maven-settings-3.0.4.jar:\
/jhome/rthummalapenta/.m2/repository/org/apache/maven/maven-settings-builder/3.0.4/maven-settings-builder-3.0.4.jar:\
/jhome/rthummalapenta/.m2/repository/org/apache/maven/maven-repository-metadata/3.0.4/maven-repository-metadata-3.0.4.jar:\
/jhome/rthummalapenta/.m2/repository/org/apache/maven/maven-plugin-api/3.0.4/maven-plugin-api-3.0.4.jar:\
/jhome/rthummalapenta/.m2/repository/org/apache/maven/maven-model-builder/3.0.4/maven-model-builder-3.0.4.jar:\
/jhome/rthummalapenta/.m2/repository/org/apache/maven/maven-aether-provider/3.0.4/maven-aether-provider-3.0.4.jar:\
/jhome/rthummalapenta/.m2/repository/org/sonatype/aether/aether-spi/1.13.1/aether-spi-1.13.1.jar:\
/jhome/rthummalapenta/.m2/repository/org/sonatype/aether/aether-impl/1.13.1/aether-impl-1.13.1.jar:\
/jhome/rthummalapenta/.m2/repository/org/sonatype/aether/aether-api/1.13.1/aether-api-1.13.1.jar:\
/jhome/rthummalapenta/.m2/repository/org/sonatype/aether/aether-util/1.13.1/aether-util-1.13.1.jar:\
/jhome/rthummalapenta/.m2/repository/org/sonatype/sisu/sisu-inject-plexus/2.3.0/sisu-inject-plexus-2.3.0.jar:\
/jhome/rthummalapenta/.m2/repository/org/sonatype/sisu/sisu-inject-bean/2.3.0/sisu-inject-bean-2.3.0.jar:\
/jhome/rthummalapenta/.m2/repository/org/sonatype/sisu/sisu-guice/3.1.0/sisu-guice-3.1.0-no_aop.jar:\
/jhome/rthummalapenta/.m2/repository/org/sonatype/sisu/sisu-guava/0.9.9/sisu-guava-0.9.9.jar:\
/jhome/rthummalapenta/.m2/repository/org/codehaus/plexus/plexus-interpolation/1.14/plexus-interpolation-1.14.jar:\
/jhome/rthummalapenta/.m2/repository/org/codehaus/plexus/plexus-classworlds/2.4/plexus-classworlds-2.4.jar:\
/jhome/rthummalapenta/.m2/repository/org/codehaus/plexus/plexus-component-annotations/1.5.5/plexus-component-annotations-1.5.5.jar:\
/jhome/rthummalapenta/.m2/repository/org/sonatype/plexus/plexus-sec-dispatcher/1.3/plexus-sec-dispatcher-1.3.jar:\
/jhome/rthummalapenta/.m2/repository/org/sonatype/plexus/plexus-cipher/1.4/plexus-cipher-1.4.jar:\
/jhome/rthummalapenta/.m2/repository/org/apache/maven/maven-project/3.0-alpha-2/maven-project-3.0-alpha-2.jar:\
/jhome/rthummalapenta/.m2/repository/org/apache/maven/maven-compat/3.0-alpha-2/maven-compat-3.0-alpha-2.jar:\
/jhome/rthummalapenta/.m2/repository/org/apache/maven/wagon/wagon-provider-api/1.0-beta-4/wagon-provider-api-1.0-beta-4.jar:\
/jhome/rthummalapenta/.m2/repository/org/codehaus/plexus/plexus-container-default/1.0-beta-3.0.5/plexus-container-default-1.0-beta-3.0.5.jar:\
/jhome/rthummalapenta/.m2/repository/org/apache/xbean/xbean-reflect/3.4/xbean-reflect-3.4.jar:\
/jhome/rthummalapenta/.m2/repository/commons-logging/commons-logging-api/1.1/commons-logging-api-1.1.jar:\
/jhome/rthummalapenta/.m2/repository/com/google/code/google-collections/google-collect/snapshot-20080530/google-collect-snapshot-20080530.jar:\
/jhome/rthummalapenta/.m2/repository/org/sonatype/spice/model-builder/1.3/model-builder-1.3.jar:\
/jhome/rthummalapenta/.m2/repository/org/apache/maven/maven-project-builder/3.0-alpha-2/maven-project-builder-3.0-alpha-2.jar:\
/jhome/rthummalapenta/.m2/repository/org/apache/maven/maven-artifact/3.0.4/maven-artifact-3.0.4.jar:\
/jhome/rthummalapenta/.m2/repository/org/codehaus/plexus/plexus-utils/1.5.15/plexus-utils-1.5.15.jar:\
/jhome/rthummalapenta/.m2/repository/xerces/xercesImpl/2.8.0/xercesImpl-2.8.0.jar:\
/jhome/rthummalapenta/.m2/repository/xml-apis/xml-apis/1.3.03/xml-apis-1.3.03.jar:\
/jhome/rthummalapenta/.m2/repository/org/apache/maven/shared/maven-invoker/2.1.1/maven-invoker-2.1.1.jar:\
/jhome/rthummalapenta/.m2/repository/commons-codec/commons-codec/1.4/commons-codec-1.4.jar:\
/jhome/rthummalapenta/.m2/repository/commons-io/commons-io/2.4/commons-io-2.4.jar:\
/jhome/rthummalapenta/.m2/repository/log4j/log4j/1.2.16/log4j-1.2.16.jar:\
/jhome/rthummalapenta/.m2/repository/mysql/mysql-connector-java/5.1.14/mysql-connector-java-5.1.14.jar:\
/jhome/rthummalapenta/.m2/repository/org/codehaus/woodstox/wstx-asl/3.2.7/wstx-asl-3.2.7.jar:\
/jhome/rthummalapenta/.m2/repository/stax/stax-api/1.0.1/stax-api-1.0.1.jar:\
/jhome/rthummalapenta/.m2/repository/org/beanshell/bsh/2.0b4/bsh-2.0b4.jar:\
/jhome/rthummalapenta/.m2/repository/com/google/inject/guice/2.0/guice-2.0.jar:\
/jhome/rthummalapenta/.m2/repository/aopalliance/aopalliance/1.0/aopalliance-1.0.jar:\
/jhome/rthummalapenta/.m2/repository/com/beust/jcommander/1.12/jcommander-1.12.jar:\
/jhome/rthummalapenta/.m2/repository/javax/activation/activation/1.1/activation-1.1.jar:\
/jhome/rthummalapenta/.m2/repository/javax/mail/mail/1.4.4/mail-1.4.4.jar:\
/jhome/rthummalapenta/.m2/repository/commons-net/commons-net/3.1/commons-net-3.1.jar:\
/jhome/rthummalapenta/.m2/repository/commons-lang/commons-lang/2.6/commons-lang-2.6.jar:\
/jhome/rthummalapenta/.m2/repository/commons-httpclient/commons-httpclient/3.1/commons-httpclient-3.1.jar:\
/jhome/rthummalapenta/.m2/repository/commons-logging/commons-logging/1.0.4/commons-logging-1.0.4.jar:\
/jhome/rthummalapenta/.m2/repository/org/apache/httpcomponents/httpclient/4.2.6/httpclient-4.2.6.jar:\
/jhome/rthummalapenta/.m2/repository/org/apache/httpcomponents/httpcore/4.2.5/httpcore-4.2.5.jar:\
/jhome/rthummalapenta/.m2/repository/org/apache/lucene/lucene-core/3.0.3/lucene-core-3.0.3.jar

java -cp $CLASSPATH org.docker.hackathon.depbuilder.Main -srchome /jhome/rthummalapenta/work/dochack
